// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3Dw9Ub8T8XJlNseg-7hGFGut-I-8W18',
    appId: '1:749749866856:web:a4d1d2ad75354a926106dd',
    messagingSenderId: '749749866856',
    projectId: 'finalprojectmp',
    authDomain: 'finalprojectmp.firebaseapp.com',
    storageBucket: 'finalprojectmp.firebasestorage.app',
    measurementId: 'G-5D5TZ56SH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOvSZLZk4YWqFYAsMBIknfx30ubF43cFk',
    appId: '1:749749866856:android:29c1667f1504210e6106dd',
    messagingSenderId: '749749866856',
    projectId: 'finalprojectmp',
    storageBucket: 'finalprojectmp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8XClvLuJuICt8Jisi6u6r799y7HH6Og8',
    appId: '1:749749866856:ios:b74bf5398d0ccdff6106dd',
    messagingSenderId: '749749866856',
    projectId: 'finalprojectmp',
    storageBucket: 'finalprojectmp.firebasestorage.app',
    iosBundleId: 'com.example.finalprojectMp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8XClvLuJuICt8Jisi6u6r799y7HH6Og8',
    appId: '1:749749866856:ios:b74bf5398d0ccdff6106dd',
    messagingSenderId: '749749866856',
    projectId: 'finalprojectmp',
    storageBucket: 'finalprojectmp.firebasestorage.app',
    iosBundleId: 'com.example.finalprojectMp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe3Dw9Ub8T8XJlNseg-7hGFGut-I-8W18',
    appId: '1:749749866856:web:207d76a25a36e5e66106dd',
    messagingSenderId: '749749866856',
    projectId: 'finalprojectmp',
    authDomain: 'finalprojectmp.firebaseapp.com',
    storageBucket: 'finalprojectmp.firebasestorage.app',
    measurementId: 'G-D87ZKM61E8',
  );
}
